site/back/src/Entity/Part.php
<?php

namespace App\Entity;

use App\Repository\PartRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PartRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Part
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\OneToMany(mappedBy: 'part', targetEntity: Question::class)]
    private $question;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $created_at;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $updated_at;

    #[ORM\ManyToOne(targetEntity: Chapter::class, inversedBy: 'parts')]
    private $chapter;

    public function __construct()
    {
        $this->question = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestion(): Collection
    {
        return $this->question;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->question->contains($question)) {
            $this->question[] = $question;
            $question->setPart($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->question->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getPart() === $this) {
                $question->setPart(null);
            }
        }

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt($created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt($updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getChapter(): ?Chapter
    {
        return $this->chapter;
    }

    public function setChapter(?Chapter $chapter): self
    {
        $this->chapter = $chapter;

        return $this;
    }

    #[ORM\PrePersist]
    public function beforePersist(): void
    {
        $this->created_at = new \DateTime();
    }

    #[ORM\PreUpdate]
    public function beforeUpdate(): void
    {
        $this->updated_at = new \DateTime();
    }

    public function __toString(): string
    {
        return $this->title;
    }
}

site/back/src/Form/PartType.php
<?php

namespace App\Form;

use App\Entity\Chapter;
use App\Entity\Part;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('content', TextType::class, ['invalid_message' => 'The content value is invalid'])
            ->add('title', TextType::class, ['invalid_message' => 'The title value is invalid'])
            ->add('chapter', EntityType::class, ['class' => Chapter::class, 'invalid_message' => 'the chapter value is invalid'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Part::class,
            'csrf_protection' => false,
            'allow_extra_fields' => true,
        ]);
    }
}

site/back/src/Controller/PartController.php
<?php

namespace App\Controller;

use App\Entity\Part;
use App\Entity\Question;
use App\Form\PartType;
use App\Normalizer\PartNormalizer;
use App\Repository\PartRepository;
use Doctrine\Persistence\ManagerRegistry;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/part', name: 'part')]
class PartController extends AbstractController
{
    private PartRepository $partRepository;
    private ManagerRegistry $doctrine;
    private array $status = ['result' => 'success', 'msg' => ''];


    public function __construct(PartRepository $partRepository, ManagerRegistry $doctrine)
    {
        $this->partRepository = $partRepository;
        $this->doctrine = $doctrine;
    }

    /**
     * List parts
     * @return JsonResponse
     */
    #[Route('/list', name: '_list', methods: ['GET'])]
    public function list(): JsonResponse
    {
        try {
            $part = $this->partRepository->findAll();
            $normalizer = PartNormalizer::listNormalizer($part);
            $response = ['result' => $this->status['result'], 'msg' => $this->status['msg'], 'data' => $normalizer];
        } catch (Exception $e) {
            $this->status['result'] = "error";
            $response = ['result' => $this->status['result'], 'msg' => sprintf('Exception thrown : "%s"', $e->getMessage())];
        }

        return new JsonResponse($response);
    }

    /**
     * Show a part details
     *
     * @param Request $request
     * @return JsonResponse
     */
    #[Route('/show', name: '_show', requirements: ["id" => "^[1-9]\d*$"], methods: ['GET'])]
    public function show(Request $request): JsonResponse
    {
        try {
            $id = $request->get('id');
            $part = $this->partRepository->find($id);
            if ($part === null) {
                $this->status['result'] = "error";
                $this->status['msg'] = "Requested part not found.";
            } else {
                $normalizer = PartNormalizer::showNormalizer($part);
            }

            $response = ['result' => $this->status['result'], 'msg' => $this->status['msg'], 'data' => $normalizer ?? []];
        } catch (Exception $e) {
            $this->status['result'] = "error";
            $response = ['result' => $this->status['result'], 'msg' => sprintf('Exception thrown : "%s"', $e->getMessage()), 'data' => []];
        }

        return new JsonResponse($response);
    }

    /**
     * Add a part
     *
     * @param Request $request
     * @return JsonResponse
     */
    #[Route('/add', name: '_add', methods: ['POST'])]
    public function add(Request $request): JsonResponse
    {
        try {
            $em = $this->doctrine->getManager();
            $content = json_decode($request->getContent(), true, 512, JSON_THROW_ON_ERROR);

            $part = new Part();
            $form = $this->createForm(PartType::class, $part);

            $content['question'] = isset($content['question']) ? $this->findQuestion($content['question'])->getId() : [];

            $request->request->add($content);
            $form->submit($request->request->all(), true);

            if ($form->isSubmitted() && $form->isValid()) {
                $em->persist($part);
                $em->flush();

                $this->status['msg'] = "Part added.";
            } else if ($form->isSubmitted() && !$form->isValid()) {
                $this->status['result'] = "error";
                $this->status['msg'] = sprintf('Error in form: "%s"', $form->getErrors(true)->current()->getMessage());
            }

            $response = ['result' => $this->status['result'], 'msg' => $this->status['msg'], 'partId' => $part->getId()];
        } catch (Exception $e) {
            $this->status['result'] = "error";
            $response = ['result' => $this->status['result'], 'msg' => sprintf('Exception thrown : "%s"', $e->getMessage()), 'data' => []];
        }

        return new JsonResponse($response);
    }

    /**
     * Edit a part
     *
     * @param Request $request
     * @return JsonResponse
     */
    #[Route('/edit', name: '_edit', methods: ['PATCH'])]
    public function edit(Request $request): JsonResponse
    {
        try {
            $em = $this->doctrine->getManager();
            $content = json_decode($request->getContent(), true, 512, JSON_THROW_ON_ERROR);
            $id = $content['id'];
            $part = $this->partRepository->find($id);

            if ($part === null) {
                $this->status['result'] = "error";
                $this->status['msg'] = "Requested part not found.";
            } else {
                $form = $this->createForm(PartType::class, $part);

                $content['question'] = isset($content['question']) ? $this->findQuestion($content['question'])->getId() : [];

                $request->request->add($content);
                $form->submit($request->request->all(), true);

                if ($form->isSubmitted() && $form->isValid()) {
                    $em->persist($part);
                    $em->flush();

                    $this->status['msg'] = "Part edited.";
                } else if ($form->isSubmitted() && !$form->isValid()) {
                    $this->status['result'] = "error";
                    $this->status['msg'] = sprintf('Error in form: "%s"', $form->getErrors(true)->current()->getMessage());
                }
            }

            $response = ['result' => $this->status['result'], 'msg' => $this->status['msg']];
        } catch (Exception $e) {
            $this->status['result'] = "error";
            $response = ['result' => $this->status['result'], 'msg' => sprintf('Exception thrown : "%s"', $e->getMessage()), 'data' => []];
        }

        return new JsonResponse($response);
    }

    /**
     * Delete a part
     *
     * @param Request $request
     * @return JsonResponse
     */
    #[Route('/delete', name: '_delete', requirements: ["id" => "^[1-9]\d*$"], methods: ['DELETE'])]
    public function delete(Request $request): JsonResponse
    {
        try {
            $em = $this->doctrine->getManager();
            $id = $request->get('id');
            $part = $this->partRepository->find($id);

            if ($part === null) {
                $this->status['result'] = "error";
                $this->status['msg'] = "Requested part not found.";
            } else {
                $em->remove($part);
                $em->flush();

                $this->status['msg'] = "Part deleted.";
            }

            $response = ['result' => $this->status['result'], 'msg' => $this->status['msg']];
        } catch (Exception $e) {
            $this->status['result'] = "error";
            $response = ['result' => $this->status['result'], 'msg' => sprintf('Exception thrown : "%s"', $e->getMessage()), 'data' => []];
        }

        return new JsonResponse($response);
    }

    /**`
     * Find a question from an integer
     * @param int $data
     * @return Question
     */
    public function findQuestion(int $data): Question
    {
        return $this->doctrine->getRepository(Question::class)->find($data);
    }
}

site/back/templates/part/_delete_form.html.twig
<form method="post" action="{{ path('app_part_delete', {'id': part.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ part.id) }}">
    <button class="btn">Delete</button>
</form>

site/back/templates/part/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

site/back/templates/part/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Part{% endblock %}

{% block body %}
    <h1>Edit Part</h1>

    {{ include('part/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_part_index') }}">back to list</a>

    {{ include('part/_delete_form.html.twig') }}
{% endblock %}

site/back/templates/part/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Part index{% endblock %}

{% block body %}
    <h1>Part index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Content</th>
                <th>Title</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for part in parts %}
            <tr>
                <td>{{ part.id }}</td>
                <td>{{ part.content }}</td>
                <td>{{ part.title }}</td>
                <td>{{ part.createdAt ? part.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ part.updatedAt ? part.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_part_show', {'id': part.id}) }}">show</a>
                    <a href="{{ path('app_part_edit', {'id': part.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_part_new') }}">Create new</a>
{% endblock %}

site/back/templates/part/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Part{% endblock %}

{% block body %}
    <h1>Create new Part</h1>

    {{ include('part/_form.html.twig') }}

    <a href="{{ path('app_part_index') }}">back to list</a>
{% endblock %}

site/back/templates/part/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Part{% endblock %}

{% block body %}
    <h1>Part</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ part.id }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ part.content }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ part.title }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ part.createdAt ? part.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ part.updatedAt ? part.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_part_index') }}">back to list</a>

    <a href="{{ path('app_part_edit', {'id': part.id}) }}">edit</a>

    {{ include('part/_delete_form.html.twig') }}
{% endblock %}